<?php

namespace Fsb\Alfred\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NoResultException;

/**
 * InsuranceFeeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InsuranceFeeRepository extends EntityRepository
{
    public function findAll()
    {
        $qb = $this->_em->createQueryBuilder();

        $qb->select('if')
            ->from('FsbAlfredCoreBundle:InsuranceFee', 'if')
            ->where($qb->expr()->eq('if.isHidden', ':isHidden'))
            ->setParameter('isHidden', false)
        ;

        return $qb->getQuery()->getResult();
    }

    public function getTotalPrice()
    {
        $price = 0;

        $qb = $this->_em->createQueryBuilder();

        $qb->select('SUM(if.price) price')
            ->from('FsbAlfredCoreBundle:InsuranceFee', 'if')
            ->where($qb->expr()->eq('if.isHidden', ':isHidden'))
            ->setParameter('isHidden', false)
        ;

        try {
            $result = $qb->getQuery()->getSingleResult();
            $price = (float) $result['price'];
        }
        catch (NoResultException $e) {}

        return $price;
    }
}
